### PR TITLE
Tangle.md: stack init -> stack.yaml; update README and Main.hs

### PR DESCRIPTION
**Pull request by dgrisham**
Correctly fixing what https://github.com/ehildenb/pandoc-tangle/pull/4 was intended for. Also, `src/Main.hs` was out of sync with `Tangle.md`, so that's fixed as well. I can do that in a separate PR as well, but that would be kind of messy.

### CODE REVIEW

**Comment by dgrisham** [comment]
@dwightguth This should be good now!

**Review by dwightguth — CHANGES_REQUESTED** [review]
I believe that Main.hs is correct and Tangle.md is actually wrong in this case.

**Comment by dgrisham** [comment]
Ah, okay, I'll revert that.

**Comment by dwightguth** [comment]
At least with regards to the monoid operator

**Comment by dgrisham** [comment]
@dwightguth updated

**Review by dwightguth — APPROVED** [review]

**Pull request merged**
